// this file is generated by ChatGPT for testing purposes
import React from 'react';

function About() {
	return (
		<div>
			<h2>About</h2>
			<p>This is the About page.</p>
		</div>
	);
}

export default About;
