// note: all functions in this file are designed by shibo including signature and name, but are implemented by copilot
export class Dataset {
	public datasetName: string;
	public courses: Course[];
	// generated by copilot
	constructor(datasetName: string) {
		this.datasetName = datasetName;
		this.courses = [];
	}
	// generated by copilot
	public addCourse(course: Course): void {
		this.courses.push(course);
	}
}

export class Course {
	public courseName: string;
	public sections: Section[];
	// generated by copilot
	constructor(courseName: string) {
		this.courseName = courseName;
		this.sections = [];
	}
	// generated by copilot
	public addSection(section: Section): void {
		this.sections.push(section);
	}
}

export class Section {
	public avg: number;
	public dept: string;
	public id: string;
	public instructor: string;
	public title: string;
	public pass: number;
	public fail: number;
	public audit: number;
	public uuid: string;
	public year: number;
	// constructor generated by copilot
	constructor(avg: number, dept: string, id: string, instructor: string, title: string, pass: number, fail: number,
		audit: number, uuid: string, year: number) {
		this.avg = avg;
		this.dept = dept;
		this.id = id;
		this.instructor = instructor;
		this.title = title;
		this.pass = pass;
		this.fail = fail;
		this.audit = audit;
		this.uuid = uuid;
		this.year = year;
	}
}

