import {Section} from "./Courses";
import {QueryResult} from "./QueryTypes";
// this file is generated by chatgpt, the design and prompt were done by shibo
export function areObjectsEqual(section1: any, section2: any): boolean {
	if (section1 instanceof Section && section2 instanceof Section) {
		return section1.avg === section2.avg &&
			section1.dept === section2.dept &&
			section1.id === section2.id &&
			section1.instructor === section2.instructor &&
			section1.title === section2.title &&
			section1.pass === section2.pass &&
			section1.fail === section2.fail &&
			section1.audit === section2.audit &&
			section1.uuid === section2.uuid &&
			section1.year === section2.year;
	} else {
		return section1.fullname === section2.fullname &&
			section1.shortname === section2.shortname &&
			section1.number === section2.number &&
			section1.name === section2.name &&
			section1.address === section2.address &&
			section1.lat === section2.lat &&
			section1.lon === section2.lon &&
			section1.seats === section2.seats &&
			section1.type === section2.type &&
			section1.furniture === section2.furniture &&
			section1.href === section2.href;
	}
}

export function unionOfQueryResults(res1: QueryResult, res2: QueryResult): QueryResult {
	const unionResult = new QueryResult();
	const allSections = [...res1.getElements(), ...res2.getElements()];
	for (const section of allSections) {
		if (!unionResult.hasElement(section)) {
			unionResult.addElement(section);
		}
	}
	return unionResult;
}

export function intersectionOfQueryResults(res1: QueryResult, res2: QueryResult): QueryResult {
	const intersectionResult = new QueryResult();
	for (const section1 of res1.getElements()) {
		if (res2.getElements().some((section2) => areObjectsEqual(section1, section2))) {
			intersectionResult.addElement(section1);
		}
	}
	return intersectionResult;
}

export function differenceOfQueryResults(res1: QueryResult, res2: QueryResult): QueryResult {
	const differenceResult = new QueryResult();

	// Convert each section of res2 into a serialized form and add to a Set
	const res2Set = new Set(res2.getElements().map((section) => JSON.stringify(section)));

	for (const section1 of res1.getElements()) {
		const serializedSection1 = JSON.stringify(section1);
		if (!res2Set.has(serializedSection1)) {
			differenceResult.addElement(section1);
		}
	}

	return differenceResult;
}

